- name: "nginx install and run"
  hosts: web
  tasks:
    - name: install nginx
      ansible.builtin.package:    #heterogenous module that can work for all distros
        name: nginx
        state: installed