- name: variables to print
  hosts: web
  tasks: 
    - name: print the inforamtion
      ansible.builtin.service:
        msg: "Hi, I am learning DevOps with AWS, Duration:120 hours; trainer: Shiva Kumar Reddy"