- name: variables to print
  hosts: web
  vars: 
    COURSE: "DevOps with AWS"
    DURATION: "120hrs"
    TRAINER: "Sivakumar Reddy M "
  tasks: 
    - name: print the inforamtion
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration: {{DURATION1}}; trainer: {{TRAINER}}"