- name: variables from files
  hosts: web
  vars_files:  #giving reference to the vars files
  - vars.yaml
  tasks:
    - name: print the course information
      ansible.builtin.debug:
      msg: " Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer: {{TRAINER}} "
