- name: Variable to print
  hosts: web
  
  # Place vars_prompt here, not under vars
  vars_prompt:  
    - name: COURSE
      prompt: "Please enter the course name"
      private: false  # not confidential

  vars: 
    COURSE: "DevOps with AWS from PLAY LEVEL"
    DURATION: "120HRS"
    TRAINER: "Shiva kumar Reddy M"
    
  tasks:
    - name: print the information
      vars:
        #COURSE: "DevOps with AWS from TASK LEVEL"
        DURATION: "120HRS"
        TRAINER: "Shiva kumar Reddy M"
      ansible.builtin.debug:
        msg: "Hi I am learning {{COURSE}}"
 

 # 01 first preference is always to command line/args
 # 02 second to task level