- name: check a number is less than 10 or not
  hosts: localhost
  connection: local
  vars_prompt:
     - name: number
       prompt: Please enter a number
       private: false #not confidential
  tasks:
     - name: print this if less than 10
       ansible.builtin.debug:
           msg: "Given number {{ number }} is less than 10"
       when: number | int < 10   

     - name: print this if greater than or equal to 10
       ansible.builtin.debug:
         msg: "Given number {{ number }} is greather than or equal to 10"
       when: number | int >= 10  


     
