- name: create user
  hosts: web
  become: yes
  tasks:
    - name: check user exists or not
      ansible.builtin.command: id expense
      register: USER # here user is a variable that gets output from above command 
      ignore_errors: True

    - name: print the user information
      ansible.builtin.debug:
        msg: "user info: {{USER}}"

    - name: create user
      ansible.builtin.command: useradd expense
      when: USER is define and USER.rc != 0